on:
  push:
    branches:
      - main
jobs:
  test:
    name: Test
    strategy:
      matrix:
        # os: [macos-latest, ubuntu-latest, windows-latest]
        os: [windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup pnpm
        uses: pnpm/action-setup@v2.2.4
        with:
          version: 7.12.2
          run_install: |
            - recursive: true
      - name: Install sg
        run: pnpm install @ast-grep/cli -g
      - name: Debug
        run: C:\Users\runneradmin\AppData\Local\pnpm\global\5\node_modules\@ast-grep\cli\sg.exe
      - name: Compile
        run: pnpm compile
      - name: Run headless test
        uses: GabrielBB/xvfb-action@v1.0
        with:
          run: pnpm test
