on:
  push:
    branches:
      - main
jobs:
  test:
    name: Test
    strategy:
      matrix:
        # os: [macos-latest, ubuntu-latest, windows-latest]
        os: [windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install sg
        run: npm install @ast-grep/cli -g
      - name: Debug
        run: npm list -g
      - name: Install deps
        run: npm install
      - name: Compile
        run: npm run compile
      - name: Run headless test
        uses: GabrielBB/xvfb-action@v1.0
        with:
          run: npm test
